runtime: python39 # Menggunakan runtime standar untuk hosting HTML statis
service: annas-client # Nama layanan App Engine, bisa diubah sesuai kebutuhan
instance_class: F1 # Kelas instance untuk App Engine (F1 adalah kelas standar yang ringan)

handlers:
  - url: /
    static_files: index.html
    upload: index.html

  - url: /auth
    static_files: auth.html
    upload: auth.html

  - url: /images/(.*)
    static_files: images/\1
    upload: images/(.*)

  - url: /scripts/(.*)
    static_files: scripts/\1
    upload: scripts/(.*)

  - url: /styles/(.*)
    static_files: styles/\1
    upload: styles/(.*)

  - url: /(.*)
    static_files: \1
    upload: (.*)

default_expiration: "1h"
# Mengatur secure_cookies untuk keamanan
# secure_cookies: true
